// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD6w50962Q7XDBslmU82MnCqL4z0cQ3g2Q',
    appId: '1:853313145583:web:22b4f0b240b446a4f0291a',
    messagingSenderId: '853313145583',
    projectId: 'mood-diary-app-d8828',
    authDomain: 'mood-diary-app-d8828.firebaseapp.com',
    storageBucket: 'mood-diary-app-d8828.firebasestorage.app',
    measurementId: 'G-5F3D5CBDHG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDzwwiPz4GJmwVCMnPO5r-iclQannxk5rg',
    appId: '1:853313145583:android:b862071020ec7b5cf0291a',
    messagingSenderId: '853313145583',
    projectId: 'mood-diary-app-d8828',
    storageBucket: 'mood-diary-app-d8828.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyANuoWdr0rmOfZLs8bsPmxLxSkgdHvN1YU',
    appId: '1:853313145583:ios:ba017493c36d9cdff0291a',
    messagingSenderId: '853313145583',
    projectId: 'mood-diary-app-d8828',
    storageBucket: 'mood-diary-app-d8828.firebasestorage.app',
    iosBundleId: 'com.example.moodDiary',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyANuoWdr0rmOfZLs8bsPmxLxSkgdHvN1YU',
    appId: '1:853313145583:ios:ba017493c36d9cdff0291a',
    messagingSenderId: '853313145583',
    projectId: 'mood-diary-app-d8828',
    storageBucket: 'mood-diary-app-d8828.firebasestorage.app',
    iosBundleId: 'com.example.moodDiary',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD6w50962Q7XDBslmU82MnCqL4z0cQ3g2Q',
    appId: '1:853313145583:web:c7aa640bee771368f0291a',
    messagingSenderId: '853313145583',
    projectId: 'mood-diary-app-d8828',
    authDomain: 'mood-diary-app-d8828.firebaseapp.com',
    storageBucket: 'mood-diary-app-d8828.firebasestorage.app',
    measurementId: 'G-6VVVKTFHWC',
  );
}
